// Generated by tools/generate-types.php. Do not edit manually.

/* This file was automatically generated by the typescript:generate command. */
export enum FlowStatus {
  PENDING = 'pending',
  RUNNING = 'running',
  ATTENTION = 'attention',
  COMPLETED = 'completed',
  BLOCKED = 'blocked',
}

/* This file was automatically generated by the typescript:generate command. */
export enum StepStatus {
  PENDING = 'pending',
  RUNNING = 'running',
  COMPLETED = 'completed',
  FAILED = 'failed',
  SKIPPED = 'skipped',
}

/* This file was automatically generated by the typescript:generate command. */
export enum PresentationKind {
  BANNER = 'banner',
  CARD = 'card',
  INLINE = 'inline',
  TOAST = 'toast',
}

/* This file was automatically generated by the typescript:generate command. */
export enum FlowEventType {
  STARTED = 'started',
  STEP_STARTED = 'step_started',
  STEP_COMPLETED = 'step_completed',
  STEP_FAILED = 'step_failed',
  STEP_SKIPPED = 'step_skipped',
  STEP_DEFERRED = 'step_deferred',
  COMPLETED = 'completed',
  ATTENTION_REQUIRED = 'attention_required',
  BLOCKED = 'blocked',
  RESET = 'reset',
}

/* This file was automatically generated by the typescript:generate command. */
export type StepDefinition = {
  id: string;
  label: string;
  critical: boolean;
  retriable: boolean;
  dependsOn: Array<any>;
  metadata: Array<any>;
  retryPolicy: FlowRetryPolicy;
};

/* This file was automatically generated by the typescript:generate command. */
export type FlowDefinition = {
  key: string;
  steps: Array<any>;
  metadata: Array<any>;
  version: number;
};

/* This file was automatically generated by the typescript:generate command. */
export type StepState = {
  status: StepStatus;
  message: string;
  error: string;
  updatedAt: string;
  retriable: boolean;
  attempts: number;
  nextRetryAt: number;
  metadata: Array<any>;
};

/* This file was automatically generated by the typescript:generate command. */
export type FlowState = {
  status: FlowStatus;
  steps: Array<any>;
  currentStep: string;
  failedSteps: Array<any>;
  canRetryStep: string;
  message: string;
  metadata: Array<any>;
  version: number;
};

/* This file was automatically generated by the typescript:generate command. */
export type FlowAction = {
  key: string;
  label: string;
  payload: Array<any>;
  enabled: boolean;
  metadata: Array<any>;
};

/* This file was automatically generated by the typescript:generate command. */
export type FlowPresentation = {
  kind: PresentationKind;
  severity: string;
  title: string;
  message: string;
  actions: Array<any>;
  dismissible: boolean;
  metadata: Array<any>;
};

/* This file was automatically generated by the typescript:generate command. */
export type FlowRetryPolicy = {
  enabled: boolean;
  maxAttempts: number;
  backoffSeconds: number;
  idempotent: boolean;
};

/* This file was automatically generated by the typescript:generate command. */
export type FlowEvent = {
  type: FlowEventType;
  flowKey: string;
  stepId: string;
  payload: Array<any>;
  occurredAt: string;
};

