<?php

declare(strict_types=1);

use Paneon\PhpToTypeScript\Parser\PhpDocParser;
use Paneon\PhpToTypeScript\Services\ParserService;
use Psr\Log\NullLogger;

require dirname(__DIR__).'/vendor/autoload.php';

$parser = new ParserService(new NullLogger(), new PhpDocParser());
$parser->setExport(true)->setUseType(true)->setSingleFileMode(true);

$files = [
    'src/Enums/FlowStatus.php',
    'src/Enums/FlowStepStatus.php',
    'src/Enums/FlowEventType.php',
    'src/ValueObjects/StepDefinition.php',
    'src/ValueObjects/FlowDefinition.php',
    'src/ValueObjects/StepState.php',
    'src/ValueObjects/FlowState.php',
    'src/ValueObjects/FlowAction.php',
    'src/ValueObjects/FlowPresentation.php',
    'src/ValueObjects/FlowRetryPolicy.php',
    'src/ValueObjects/FlowEvent.php',
];

$output = "// Generated by tools/generate-types.php. Do not edit manually.\n\n";

foreach ($files as $file) {
    // The package's public value objects are intentionally not coupled to the
    // generator's runtime attribute, so opt into exporting each selected file.
    $output .= ($parser->getContent(__DIR__.'/../'.$file, requireAttribute: false) ?? '')."\n\n";
}

file_put_contents(__DIR__.'/../types/web-flow.generated.ts', $output);
